In [10]:
import torch

# create two 2x3 tensors
tensor_0 = torch.tensor([], dtype=int)
tensor_a = torch.tensor([[1, 2, 3 ,10, 11, 12], 
                         [4, 5, 6 ,10, 11, 12], [4, 5, 6 ,10, 11, 12]]) # image group
tensor_b = torch.tensor([7, 8, 9 ,10, 11, 12]) #image
tensor_d = torch.tensor([[6, 8, 9 ,10, 12, 12]]) #image

# tensor_c = torch.cat((tensor_0, tensor_b), dim=0)
tensor_e = torch.cat((tensor_a, tensor_d), dim=1)
# tensor_e = torch.hstack((tensor_a, tensor_d))

tensor_e

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 1 for tensor number 1 in the list.

In [1]:
import torch
import os
import pickle
import glob
import numpy as np

data_path = "/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/"

search_path = os.path.join(data_path,  "2022-12-*", "raw", "traj_group*", "traj*")
all_traj = glob.glob(search_path)

In [2]:
def load_actions(path):  # gets actions
    fp = os.path.join(path, "policy_out.pkl")
    with open(fp, "rb") as f:
        act_list = pickle.load(f)
    if isinstance(act_list[0], dict):
        act_list = [x["actions"] for x in act_list]
    return act_list #arrays of 7 elements each

In [25]:
filenames = np.array([])
actions = np.empty((0,7))
for folder in all_traj:
    # get all images
    images_files = glob.glob(os.path.join(folder , "images0", "im_*.jpg"))
    filenames = np.append(filenames, images_files)
    action = load_actions(folder)[:-1]
    action_np = np.stack(action, axis=0)
    actions =  np.append(actions, action_np, axis=0)

In [26]:
len(actions)

17862

In [27]:
len(filenames)

18952

In [21]:
folder = '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/'
images_files = glob.glob(os.path.join( folder, "images0", "im_*.jpg"))
action = load_actions(folder)
print(len(images_files))
action_np = np.stack(action, axis=0)
print(len(action))
print(len(action_np))

30
29
29


In [16]:
images_files

['/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_0.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_1.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_10.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_11.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_12.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_13.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_14.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_15.jpg',
 '/mnt/d/Downloads-D/scrip

In [ ]:
fp = os.path.join(path, "policy_out.pkl")
with open(fp, "rb") as f:
    act_list = pickle.load(f)
if isinstance(act_list[0], dict):
    act_list = [x["actions"] for x in act_list]

In [11]:
action

[array([ 0.0059266 ,  0.01823197, -0.00340325, -0.01000032, -0.03276486,
        -0.12609825,  0.99514631]),
 array([ 0.00219516,  0.02663597, -0.00130658, -0.01245689, -0.05132087,
        -0.12020946,  0.99189079]),
 array([ 1.69908790e-04,  2.59602930e-02, -3.35035543e-03, -8.12198020e-04,
        -5.35343178e-02, -1.21866407e-01,  9.95230083e-01]),
 array([-6.00158141e-04,  1.92359860e-02, -1.53643288e-03, -6.51098928e-03,
        -4.94946236e-02, -8.25346751e-02,  1.00000000e+00]),
 array([ 0.00687186,  0.02080883,  0.01829451,  0.00536978, -0.0196746 ,
        -0.07523854,  1.        ]),
 array([ 0.00161634,  0.02238659, -0.00242218, -0.00099999,  0.00378511,
        -0.0513855 ,  0.99974116]),
 array([-0.00473054,  0.0047678 , -0.00144936,  0.01454476,  0.01662228,
        -0.03786786,  1.        ]),
 array([-0.00596411,  0.01054694,  0.00354643,  0.00970004,  0.02600855,
        -0.0153109 ,  0.99927315]),
 array([-0.00207646,  0.00379302,  0.00334858,  0.00641152,  0.02124396,

In [10]:
action_np

array([[ 5.92659885e-03,  1.82319724e-02, -3.40324534e-03,
        -1.00003168e-02, -3.27648562e-02, -1.26098251e-01,
         9.95146307e-01],
       [ 2.19515886e-03,  2.66359716e-02, -1.30657758e-03,
        -1.24568869e-02, -5.13208744e-02, -1.20209460e-01,
         9.91890785e-01],
       [ 1.69908790e-04,  2.59602930e-02, -3.35035543e-03,
        -8.12198020e-04, -5.35343178e-02, -1.21866407e-01,
         9.95230083e-01],
       [-6.00158141e-04,  1.92359860e-02, -1.53643288e-03,
        -6.51098928e-03, -4.94946236e-02, -8.25346751e-02,
         1.00000000e+00],
       [ 6.87185845e-03,  2.08088290e-02,  1.82945116e-02,
         5.36977900e-03, -1.96746010e-02, -7.52385420e-02,
         1.00000000e+00],
       [ 1.61634097e-03,  2.23865877e-02, -2.42218318e-03,
        -9.99991037e-04,  3.78511443e-03, -5.13854987e-02,
         9.99741165e-01],
       [-4.73053868e-03,  4.76779576e-03, -1.44936102e-03,
         1.45447553e-02,  1.66222804e-02, -3.78678605e-02,
         1.0000000

In [3]:
images_files = glob.glob(os.path.join(all_traj[0] , "images0", "im_*.jpg"))
images_files

['/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_0.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_1.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_10.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_11.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_12.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_13.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_14.jpg',
 '/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/images0/im_15.jpg',
 '/mnt/d/Downloads-D/scrip

In [4]:
actions_files =  glob.glob(os.path.join(all_traj[0] , "policy_out.pkl"))
actions_files

['/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0/policy_out.pkl']

In [25]:
import torch
import os
import pickle
import glob
import numpy as np
from PIL import Image

data_path = "/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/"

class BerkeleyDataset(torch.utils.data.Dataset):

    def __init__(self):
        search_path = os.path.join(data_path,  "2022-12-*", "raw", "traj_group*", "traj*")
        all_traj = glob.glob(search_path)
        self.filenames = np.array([])
        self.actions = np.empty((0,7))
        for folder in all_traj:
            # get all images
            images_files = glob.glob(os.path.join(folder , "images0", "im_*.jpg"))
            self.filenames = np.append(self.filenames, images_files[1:])
            action = self.load_actions(folder)
            action_np = np.stack(action, axis=0)
            self.actions =  np.append(self.actions, action_np, axis=0)

    def __getitem__(self, idx):
        item = {}
        # load image and corresponding action
        image =  Image.open(self.filenames[idx])
        action = self.actions[idx]
        item['image'] = torch.tensor(np.array(image))
        item['action'] = torch.tensor(action)
        return item
    
    def load_actions(self, path):  # gets actions
        fp = os.path.join(path, "policy_out.pkl")
        with open(fp, "rb") as f:
            act_list = pickle.load(f)
        if isinstance(act_list[0], dict):
            act_list = [x["actions"] for x in act_list]
        return act_list #arrays of 7 elements each
    
    def __len__(self):
        return len(self.filenames) 

In [26]:
from torch.utils.data import DataLoader
dataset = BerkeleyDataset()
dataloader = DataLoader(dataset, batch_size=64, shuffle=True)

In [27]:
print(len(dataset.actions))
print(len(dataset.filenames))

18407
18407


In [30]:
a = next(iter(dataloader))

a[0]['action']

KeyError: 0

In [ ]:
action = dataset.load_actions('/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0')

In [16]:
filenames = np.array([])
actions = np.empty((0,7))

for folder in all_traj:
    # get all images
    images_files = glob.glob(os.path.join(folder , "images0", "im_*.jpg"))
    filenames = np.append(filenames, images_files)
    print(folder)
    print("images: "+ str(len(images_files)))
    action = dataset.load_actions(folder)
    print("actions: "+ str(len(action)))
    action_np = np.stack(action, axis=0)
    actions =  np.append(actions, action_np, axis=0)

/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj0
images: 30
actions: 29
/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj1
images: 30
actions: 29
/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-56-20/raw/traj_group0/traj2
images: 30
actions: 29
/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-59-14/raw/traj_group0/traj0
images: 30
actions: 29
/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-59-14/raw/traj_group0/traj1
images: 30
actions: 29
/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-59-14/raw/traj_group0/traj10
images: 30
actions: 29
/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-59-14/raw/traj_group0/traj11
images: 30
actions: 29
/mnt/d/Downloads-D/scripted_6_18/scripted_raw/sweep_12-03/2022-12-04_14-59-14/raw/traj_group0/traj12
images: 30
actions: 29
/mnt/d/Downlo

In [ ]:
actions = np.empty((0,7))
aciton_np = np.stack(action, axis=0)
actions =  np.append(actions, aciton_np, axis=0)
actions

array([[-2.17230700e-02,  4.57776302e-02, -3.10825218e-03,
        -6.11764843e-03, -2.04061652e-02, -1.95836364e-01,
         9.97281190e-01],
       [-1.74180912e-02,  5.14687132e-02, -5.63831136e-03,
        -1.20128096e-02, -4.79751336e-02, -1.93328311e-01,
         9.89172076e-01],
       [-1.22275603e-02,  4.35717804e-02, -2.29090567e-03,
         5.68858000e-03, -4.46496858e-02, -1.41331963e-01,
         1.00000000e+00],
       [-2.75288577e-02,  3.56792977e-02,  1.06210411e-02,
         1.32328069e-02, -1.83716418e-02, -1.22587632e-01,
         1.00000000e+00],
       [-5.23159298e-03,  3.06143962e-02,  5.77714181e-03,
         2.01171747e-02, -4.97684106e-03, -9.51477640e-02,
         1.00000000e+00],
       [-8.97468404e-03,  1.92724973e-02, -4.68816489e-04,
         1.03511757e-02,  1.21088095e-02, -7.63940667e-02,
         9.97315548e-01],
       [-1.03006529e-02,  1.77663997e-02,  1.90194032e-04,
         1.11419430e-02,  8.67873884e-03, -5.00243020e-02,
         9.9734225

In [ ]:
actions[28]

array([-0.00148566, -0.00214222, -0.00269785, -0.00634548,  0.01319404,
        0.02281726, -0.0005469 ])